title: bookmark-cd
name: bcd
type: app
base: core20
version: 'v0.2.5'
summary: cd to bookmarked directories
description: |
  bcd is a way to cd to directories that have been bookmarked.

grade: stable
confinement: strict
issues: https://github.com/a1ecbr0wn/bcd/issues
website: https://bcd.noser.net
icon: img/bcd_icon.png
license: Apache-2.0

plugs:
  dot-bashrc:
    interface: personal-files
    write:
      - $HOME/.bashrc

parts:
  bookmark-cd:
    plugin: rust
    source: https://github.com/a1ecbr0wn/bcd/archive/refs/tags/v0.2.5.tar.gz

apps:
  bookmark-cd:
    command: bin/bookmark-cd

