title: bookmark-cd
name: bookmark-cd
type: app
base: core20
version: 'v1.0.23'
summary: bcd to a bookmarked directory
description: |
  `bcd` is a way to cd to directories that have been bookmarked.

  Snapcraft does not allow write access to the shell init scripts which are required to set up `bcd` so the following commmand should be set up manually in your `~/.bashrc` if you are using bash or `~/.zshrc` if you are using zsh as your shell:

     # bookmark-cd init block
     eval "$(bookmark-cd init)"   

grade: stable
confinement: strict
issues: https://github.com/a1ecbr0wn/bcd/issues
website: https://bcd.noser.net
icon: img/bcd_icon.png
license: Apache-2.0

plugs:
  dot-bashrc:
    interface: personal-files
    read:
      - $HOME/.bashrc
  dot-zshrc:
    interface: personal-files
    read:
      - $HOME/.zshrc

parts:
  bookmark-cd:
    plugin: rust
    source: https://github.com/a1ecbr0wn/bcd/archive/refs/tags/v1.0.23.tar.gz

apps:
  bookmark-cd:
    command: bin/bookmark-cd

